services:
  techdoro-builder:
    container_name: techdoro-builder
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./out:/app/out:Z
      - techdoro:/app/node_modules:Z
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
  techdoro: