version: "3.8"

services:
  techdoro-builder:
    build:
      context: .
      dockerfile: Dockerfile
    image: techdoro-builder:latest
    volumes:
      - ./out:/app/out:Z
      - ./node_modules:/app/node_modules:Z